### PR TITLE
Basic Pipeline

### PR DESCRIPTION
**Pull request by JSKenyon**
@joesbright @o-smirnov This is a much slimmer version of the original pipeline. I have made it installable so that it will automatically take care of its dependencies. It is far from complete as it has only really been tested on the ATA data which I worked on during the busy week and doesn't consider multiple rounds of selfcal or DDEs. I intend to make a few more improvements to this base version (manual specification of the field centre is an annoyance), but I think it is now tidy enough for others to potentially see/try it. I suspect that we should move it to an entirely separate repo as it has probably diverged sufficiently from the original. This PR can serve a discussion space.

### CODE REVIEW

**Comment by joesbright** [comment]
@JSKenyon Testing this on some MeerKAT data at the moment. One small issue was that I think the 

```
  steps:
    flag-save:
      info: |
        Create a backup of the original flags on the dataset. This step is only
        run when the init tag is selected.
      tags: [init, never]
      cab: casa.flagman
      params:
        ms: =recipe.ms
        mode: save
        versionname: =recipe.initial-flag-version
``` 
doesn't get run in the `stimela -C run lightcurve-pipline.yml -t init` line due to the `never` tag?

**Comment by JSKenyon** [comment]
Thanks @joesbright - this is a small bug I may have introduced in Stimela. Will sort out a fix tomorrow. For now, simply doing `stimela -C run lightcurve-pipline.yml -s flag-save` instead will work.

**Comment by JSKenyon** [comment]
PR on Stimela: https://github.com/caracal-pipeline/stimela/pull/277

**Comment by joesbright** [comment]
Thanks @JSKenyon. I also notice that 

```
    image-2:
      info: |
        Image and deconvolve the selfcal corrected data using wsclean and a
        fits mask.
      _use: lib.steps.wsclean.image_column
      params:
        fits-mask: =steps.mask-1.mask
        auto-threshold: 1
``` 

looks for the column SELFCAL2_DATA, and I think it wants SELFCAL1_DATA from the cubical step.

**Comment by JSKenyon** [comment]
> looks for the column SELFCAL2_DATA, and I think it wants SELFCAL1_DATA from the cubical step.

You are absolutely right - I think I missed this as my dataset already had all of these columns added. I will address the root case (which, I believe, has something to do with the fact that previously there was no selfcal-1 step).

**Comment by o-smirnov** [comment]
I suggest the ``=steps.selfcal-*.column`` construct for this. ``selfcal-*`` meaning the aphanumerically highest step label conforming to the pattern -- I think it's the most "robust" way to refer to the output of the most recently preceding calibration step.

**Comment by JSKenyon** [comment]
> I suggest the `=steps.selfcal-*.column` construct for this. `selfcal-*` meaning the aphanumerically highest step label conforming to the pattern -- I think it's the most "robust" way to refer to the output of the most recently preceding calibration step.

Oh brilliant! I didn't know about that. Will sort it out shortly.

**Comment by o-smirnov** [comment]
> the alphanumerically highest step label conforming to the pattern 

...among preceding steps, obviously.

**Pull request closed without merging**
